name: CI/CD ke VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy ke VPS via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Masuk ke folder aplikasi"
            cd /myapp || mkdir -p /myapp && cd /myapp

            echo "Update source code dari Git"
            git reset --hard
            git clean -fd
            git pull origin main

            echo "Stop dan hapus container lama (jika ada)"
            docker stop web || true
            docker rm web || true

            echo "Build image Docker baru"
            docker build -t myapp .

            echo "Jalankan container baru"
            docker run -d \
              --name web \
              -p 80:80 \
              --restart unless-stopped \
              myapp

          args: -o StrictHostKeyChecking=no

      - name: Cek container running
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker ps -a
