name: CI/CD ke VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy ke VPS
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}        
          username: ${{ secrets.SERVER_USER }}    
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          script: |
            echo "Masuk ke folder aplikasi"
            cd ~/myapp

            echo "Update source code"
            git fetch --all
            git reset --hard origin/main
            git clean -fd

            echo "Stop container lama (jika ada)"
            sudo docker stop web || true
            sudo docker rm web || true

            echo "Build image Docker baru"
            sudo docker build -t myapp .

            echo "Jalankan container baru"
            sudo docker run -d --name web -p 80:80 --restart unless-stopped myapp

            echo "Cek container berjalan"
            sudo docker ps -a
